In [78]:
import pandas as pd
df1=pd.read_excel("GDP/2009-2013地区生产总值.xls",usecols=[0,2,3,4,5,6],header=5)
df1.columns=['地区',2009,2010,2011,2012,2013]
df1.set_index("地区",inplace=True)
df1

         2009      2010      2011      2012      2013
地区
北京   12153.03  14113.58  16251.93  17879.40  19500.56
天津    7521.85   9224.46  11307.28  12893.88  14370.16
河北   17235.48  20394.26  24515.76  26575.01  28301.41
山西    7358.31   9200.86  11237.55  12112.83  12602.24
内蒙古   9740.25  11672.00  14359.88  15880.58  16832.38
辽宁   15212.49  18457.27  22226.70  24846.43  27077.65
吉林    7278.75   8667.58  10568.83  11939.24  12981.46
黑龙江   8587.00  10368.60  12582.00  13691.58  14382.93
上海   15046.45  17165.98  19195.69  20181.72  21602.12
江苏   34457.30  41425.48  49110.27  54058.22  59161.75
浙江   22990.35  27722.31  32318.85  34665.33  37568.49
安徽   10062.82  12359.33  15300.65  17212.05  19038.87
福建   12236.53  14737.12  17560.18  19701.78  21759.64
江西    7655.18   9451.26  11702.82  12948.88  14338.50
山东   33896.65  39169.92  45361.85  50013.24  54684.33
河南   19480.46  23092.36  26931.03  29599.31  32155.86
湖北   12961.10  15967.61  19632.26  22250.45  24668.49
湖南   13059.69  16037.96  19669.56  22154.23  24501.67
广东   39482.56  46013.06  53210.28  57067.92  62163.97
广西    7759.16   9569.85  11720.87  13035.10  14378.00
海南    1654.21   2064.50   2522.66   2855.54   3146.46
重庆    6530.01   7925.58  10011.37  11409.60  12656.69
四川   14151.28  17185.48  21026.68  23872.80  26260.77
贵州    3912.68   4602.16   5701.84   6852.20   8006.79
云南    6169.75   7224.18   8893.12  10309.47  11720.91
西藏     441.36    507.46    605.83    701.03    807.67
陕西    8169.80  10123.48  12512.30  14453.68  16045.21
甘肃    3387.56   4120.75   5020.37   5650.20   6268.01
青海    1081.27   1350.43   1670.44   1893.54   2101.05
宁夏    1353.31   1689.65   2102.21   2341.29   2565.06
新疆    4277.05   5437.47   6610.05   7505.31   8360.24

In [36]:
path="GDP/{}各地区生产总值.xls"
df2=pd.read_excel(path.format(2014),usecols=[0,2],header=5)
for i in range(2015,2018):
    df2=pd.concat([df2,pd.read_excel(path.format(i),usecols=[2],header=5)],axis=1)
df2.columns=['地区',*[i for i in range(2014,2018)]]
df2.set_index("地区",inplace=True)
df2

        2014     2015     2016     2017
地区
北京   21330.8  23014.6  25669.1  28014.9
天津   15727.0  16538.2  17885.4  18549.2
河北   29421.2  29806.4  32070.5  34016.3
山西   12761.5  12766.5  13055.6  15528.4
内蒙古  17769.5  17831.5  18128.1  16096.2
辽宁   28626.6  28669.0  22246.9  23409.2
吉林   14631.4  15507.9  14776.8  14944.5
黑龙江  15275.2  15083.7  15386.1  15902.7
上海   23567.7  25123.5  28178.7  30633.0
江苏   65088.3  70116.4  77388.3  85869.8
浙江   40173.0  42886.5  47251.4  51768.3
安徽   20848.8  22005.6  24407.6  27018.0
福建   24055.8  25979.8  28810.6  32182.1
江西   14410.2  16723.8  18499.0  20006.3
山东   59426.6  63002.3  68024.5  72634.2
河南   34938.2  37002.2  40471.8  44552.8
湖北   28728.2  31226.4  32665.4  35478.1
湖南   27037.3  28902.2  31551.4  33902.7
广东   67809.9  72812.6  80854.9  89705.2
广西   15672.9  16803.1  18317.6  18523.3
海南    3500.7   3702.8   4053.2   4462.5
重庆   14262.6  15717.3  17740.6  19424.7
四川   28536.7  30053.1  32934.5  36980.2
贵州    9266.4  10502.6  11776.7  13540.8
云南   12814.6  13619.2  14788.4  16376.3
西藏     920.8   1026.4   1151.4   1310.9
陕西   17689.9  18021.9  19399.6  21898.8
甘肃    6836.8   6790.3   7200.4   7459.9
青海    2303.3   2417.1   2572.5   2624.8
宁夏    2752.1   2911.8   3168.6   3443.6
新疆    9273.5   9324.8   9649.7  10882.0

In [88]:
df3=pd.read_excel(path.format(2018),usecols=[0,2],header=8,skiprows=list(range(40,44)))
df3.columns=["地区",2018]
df3["地区"]=df3["地区"].map(lambda x:x.replace(" ",''))
df3.set_index("地区",inplace=True)
df3

         2018
地区
北京   30319.98
天津   18809.64
河北   36010.27
山西   16818.11
内蒙古  17289.22
辽宁   25315.35
吉林   15074.62
黑龙江  16361.62
上海   32679.87
江苏   92595.40
浙江   56197.15
安徽   30006.82
福建   35804.04
江西   21984.78
山东   76469.67
河南   48055.86
湖北   39366.55
湖南   36425.78
广东   97277.77
广西   20352.51
海南    4832.05
重庆   20363.19
四川   40678.13
贵州   14806.45
云南   17881.12
西藏    1477.63
陕西   24438.32
甘肃    8246.07
青海    2865.23
宁夏    3705.18
新疆   12199.08

In [89]:
# print(df3.iloc[:,[0]])
# print(df3.index==df2.index)
df4=pd.concat([df1,df2,df3],axis=1)
df4.to_excel("GDP/gdp.xlsx")
df4

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
地区,,,,,,,,,,
北京,12153.03,14113.58,16251.93,17879.40,19500.56,21330.8,23014.6,25669.1,28014.9,30319.98
天津,7521.85,9224.46,11307.28,12893.88,14370.16,15727.0,16538.2,17885.4,18549.2,18809.64
河北,17235.48,20394.26,24515.76,26575.01,28301.41,29421.2,29806.4,32070.5,34016.3,36010.27
山西,7358.31,9200.86,11237.55,12112.83,12602.24,12761.5,12766.5,13055.6,15528.4,16818.11
内蒙古,9740.25,11672.00,14359.88,15880.58,16832.38,17769.5,17831.5,18128.1,16096.2,17289.22
辽宁,15212.49,18457.27,22226.70,24846.43,27077.65,28626.6,28669.0,22246.9,23409.2,25315.35
吉林,7278.75,8667.58,10568.83,11939.24,12981.46,14631.4,15507.9,14776.8,14944.5,15074.62
黑龙江,8587.00,10368.60,12582.00,13691.58,14382.93,15275.2,15083.7,15386.1,15902.7,16361.62
上海,15046.45,17165.98,19195.69,20181.72,21602.12,23567.7,25123.5,28178.7,30633.0,32679.87
江苏,34457.30,41425.48,49110.27,54058.22,59161.75,65088.3,70116.4,77388.3,85869.8,92595.40
浙江,22990.35,27722.31,32318.85,34665.33,37568.49,40173.0,42886.5,47251.4,51768.3,56197.15
安徽,10062.82,12359.33,15300.65,17212.05,19038.87,20848.8,22005.6,24407.6,27018.0,30006.82
福建,12236.53,14737.12,17560.18,19701.78,21759.64,24055.8,25979.8,28810.6,32182.1,35804.04
江西,7655.18,9451.26,11702.82,12948.88,14338.50,14410.2,16723.8,18499.0,20006.3,21984.78
山东,33896.65,39169.92,45361.85,50013.24,54684.33,59426.6,63002.3,68024.5,72634.2,76469.67
河南,19480.46,23092.36,26931.03,29599.31,32155.86,34938.2,37002.2,40471.8,44552.8,48055.86
湖北,12961.10,15967.61,19632.26,22250.45,24668.49,28728.2,31226.4,32665.4,35478.1,39366.55
湖南,13059.69,16037.96,19669.56,22154.23,24501.67,27037.3,28902.2,31551.4,33902.7,36425.78
广东,39482.56,46013.06,53210.28,57067.92,62163.97,67809.9,72812.6,80854.9,89705.2,97277.77
广西,7759.16,9569.85,11720.87,13035.10,14378.00,15672.9,16803.1,18317.6,18523.3,20352.51
海南,1654.21,2064.50,2522.66,2855.54,3146.46,3500.7,3702.8,4053.2,4462.5,4832.05
重庆,6530.01,7925.58,10011.37,11409.60,12656.69,14262.6,15717.3,17740.6,19424.7,20363.19
四川,14151.28,17185.48,21026.68,23872.80,26260.77,28536.7,30053.1,32934.5,36980.2,40678.13
贵州,3912.68,4602.16,5701.84,6852.20,8006.79,9266.4,10502.6,11776.7,13540.8,14806.45
云南,6169.75,7224.18,8893.12,10309.47,11720.91,12814.6,13619.2,14788.4,16376.3,17881.12
西藏,441.36,507.46,605.83,701.03,807.67,920.8,1026.4,1151.4,1310.9,1477.63
陕西,8169.80,10123.48,12512.30,14453.68,16045.21,17689.9,18021.9,19399.6,21898.8,24438.32
甘肃,3387.56,4120.75,5020.37,5650.20,6268.01,6836.8,6790.3,7200.4,7459.9,8246.07
青海,1081.27,1350.43,1670.44,1893.54,2101.05,2303.3,2417.1,2572.5,2624.8,2865.23
宁夏,1353.31,1689.65,2102.21,2341.29,2565.06,2752.1,2911.8,3168.6,3443.6,3705.18
新疆,4277.05,5437.47,6610.05,7505.31,8360.24,9273.5,9324.8,9649.7,10882.0,12199.08